---
- name: Phase 2 - Apply Patch with Dynatrace Monitoring
  hosts: all
  gather_facts: no
  serial: 1
  vars:
    ansible_user: root
    ansible_password: "Ajay@426344"
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    target_build: "24859861"
    grace_period: 120
    max_wait_time: 900
    dynatrace_url: "https://ofp39563.live.dynatrace.com"
    dynatrace_token: "dt0c01.MOQDVGYZV5NLQAAUFJMYVXM4.PNI42OD4D5V33H6IV4HQKJGB2VFDGJTPV3D6TKJBTMQ35JD62QIDNUM3OJKGQMVJ"
    
  tasks:
    - name: Set timestamps
      set_fact:
        current_epoch: "{{ now().strftime('%s') }}"
        current_iso: "{{ now().isoformat() }}"
      run_once: true
      
    - name: Record Phase 2 start time
      set_fact:
        phase2_start_time: "{{ current_epoch }}"
        
    - name: Send Phase 2 start event to Dynatrace
      uri:
        url: "{{ dynatrace_url }}/api/v2/events/ingest"
        method: POST
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          eventType: "CUSTOM_INFO"
          title: "ESXi Phase 2 Reboot Started"
          properties:
            host: "{{ inventory_hostname }}"
            phase: "phase2_reboot"
            severity: "INFO"
        status_code: [200, 201, 202]
      delegate_to: localhost
      vars:
        ansible_connection: local
        
    - name: Get pre-reboot build
      raw: vmware -v | grep -o 'build-[0-9]*' | cut -d'-' -f2
      register: pre_reboot_build
      
    - name: Enter maintenance mode
      raw: esxcli system maintenanceMode set --enable true
      register: mm_enable
      
    - name: Send maintenance mode event to Dynatrace
      uri:
        url: "{{ dynatrace_url }}/api/v2/events/ingest"
        method: POST
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          eventType: "CUSTOM_INFO"
          title: "ESXi Host Entered Maintenance Mode"
          properties:
            host: "{{ inventory_hostname }}"
            phase: "phase2_reboot"
            action: "maintenance_mode_enabled"
            severity: "INFO"
        status_code: [200, 201, 202]
      delegate_to: localhost
      vars:
        ansible_connection: local
      
    - name: Record reboot start time
      set_fact:
        reboot_start_time: "{{ now().strftime('%s') }}"
      
    - name: Send reboot initiated event to Dynatrace
      uri:
        url: "{{ dynatrace_url }}/api/v2/events/ingest"
        method: POST
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          eventType: "CUSTOM_INFO"
          title: "ESXi Host Rebooting"
          properties:
            host: "{{ inventory_hostname }}"
            phase: "phase2_reboot"
            action: "reboot_initiated"
            severity: "WARNING"
        status_code: [200, 201, 202]
      delegate_to: localhost
      vars:
        ansible_connection: local
      
    - name: Initiate reboot
      raw: reboot
      async: 1
      poll: 0
      
    - name: Wait for host offline
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        state: stopped
        timeout: 120
      delegate_to: localhost
      vars:
        ansible_connection: local
      
    - name: Grace period
      pause:
        seconds: "{{ grace_period }}"
        
    - name: Wait for host online
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        state: started
        delay: 30
        timeout: "{{ max_wait_time }}"
      delegate_to: localhost
      vars:
        ansible_connection: local
      register: host_recovery
      
    - name: Send host recovered event to Dynatrace
      uri:
        url: "{{ dynatrace_url }}/api/v2/events/ingest"
        method: POST
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          eventType: "CUSTOM_INFO"
          title: "ESXi Host Back Online"
          properties:
            host: "{{ inventory_hostname }}"
            phase: "phase2_reboot"
            action: "host_recovered"
            severity: "INFO"
        status_code: [200, 201, 202]
      delegate_to: localhost
      vars:
        ansible_connection: local
      
    - name: Calculate downtime
      set_fact:
        downtime_seconds: "{{ (now().strftime('%s') | int) - (reboot_start_time | int) }}"
        
    - name: Wait for SSH ready
      wait_for_connection:
        timeout: 300
        
    - name: Exit maintenance mode
      raw: esxcli system maintenanceMode set --enable false
      
    - name: Send maintenance mode exit event to Dynatrace
      uri:
        url: "{{ dynatrace_url }}/api/v2/events/ingest"
        method: POST
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          eventType: "CUSTOM_INFO"
          title: "ESXi Host Exited Maintenance Mode"
          properties:
            host: "{{ inventory_hostname }}"
            phase: "phase2_reboot"
            action: "maintenance_mode_disabled"
            severity: "INFO"
        status_code: [200, 201, 202]
      delegate_to: localhost
      vars:
        ansible_connection: local
      
    - name: Get post-reboot build
      raw: vmware -v | grep -o 'build-[0-9]*' | cut -d'-' -f2
      register: post_reboot_build
      
    - name: Verify patch application
      set_fact:
        patch_applied: "{{ post_reboot_build.stdout | trim == target_build }}"
        phase2_duration: "{{ (now().strftime('%s') | int) - (phase2_start_time | int) }}"
        
    - name: Send Phase 2 completion metrics to Dynatrace
      uri:
        url: "{{ dynatrace_url }}/api/v2/metrics/ingest"
        method: POST
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
          Content-Type: "text/plain; charset=utf-8"
        body: |
          esxi.patch.phase2.success,host={{ inventory_hostname }} {{ 1 if patch_applied else 0 }} {{ now().strftime('%s') }}
          esxi.patch.phase2.downtime_seconds,host={{ inventory_hostname }} {{ downtime_seconds }} {{ now().strftime('%s') }}
          esxi.patch.phase2.total_duration_seconds,host={{ inventory_hostname }} {{ phase2_duration }} {{ now().strftime('%s') }}
          esxi.patch.current_build,host={{ inventory_hostname }} {{ post_reboot_build.stdout | trim }} {{ now().strftime('%s') }}
        status_code: [200, 201, 202, 204]
      delegate_to: localhost
      vars:
        ansible_connection: local
      
    - name: Send Phase 2 completion event to Dynatrace
      uri:
        url: "{{ dynatrace_url }}/api/v2/events/ingest"
        method: POST
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          eventType: "CUSTOM_INFO"
          title: "ESXi Patching {{ 'Completed Successfully' if patch_applied else 'Failed' }}"
          properties:
            host: "{{ inventory_hostname }}"
            phase: "phase2_complete"
            status: "{{ 'success' if patch_applied else 'failed' }}"
            pre_build: "{{ pre_reboot_build.stdout | trim }}"
            post_build: "{{ post_reboot_build.stdout | trim }}"
            target_build: "{{ target_build }}"
            downtime_seconds: "{{ downtime_seconds }}"
            total_duration_seconds: "{{ phase2_duration }}"
            severity: "{{ 'INFO' if patch_applied else 'ERROR' }}"
        status_code: [200, 201, 202]
      delegate_to: localhost
      vars:
        ansible_connection: local
      
    - name: Display final status
      debug:
        msg:
          - "========================================="
          - "Patch Status: {{ 'SUCCESS' if patch_applied else 'FAILED' }}"
          - "New Build: {{ post_reboot_build.stdout | trim }}"
          - "Downtime: {{ downtime_seconds }} seconds"
          - "========================================="
